### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by y-yagi** [orca-api/orca-api#4]
今のところ、このライブラリのライセンスについての記載が無いようです(見逃していたら申し訳ありません)が、こちらのライブラリのライセンスどうなりますでしょうか?

**Comment by miyucy** [comment]
ありがとうございます。
ライセンスは [Apache-2.0](https://spdx.org/licenses/Apache-2.0.html) です。

**Comment by y-yagi** [comment]
ご確認ありがとうございます！
ライセンス Apache-2.0との事了解しました。
